# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel 
latex: false

apt_packages:
  - libxml2-dev

r_github_packages: crmclean/mmetspData
