# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel 
latex: false

apt_packages:
  - libnetcdf-dev
  - netcdf-bin 
  - libgit2-dev # git2r
  - texlive-latex-recommended
  - texlive-fonts-extra

r_github_packages: crmclean/mmetspData
