# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# using https://github.com/sneumann/xcms/blob/master/.travis.yml as a template
language: r
r: bioc-devel
cache:
  packages: true
sudo: required
warnings_are_errors: false

# unfortunately apt packages are not cached
# we could use these build dependencies just in the "Build" stage and
# install their runtime libraries counter parts in "Check" but that would make
# the script more complicated and saves just a few seconds
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 [xerus] it is part of libnetcdf-dev)
      - libhdf5-dev
      - libgit2-dev # git2r
      - texlive-latex-recommended
      - texlive-fonts-extra


# before_install:
#  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

jobs:
  include:
    - stage: "Build"
      r_packages:
        - covr
        - testthat
        - knitr
        - roxygen2
      before_install:
        - mkdir -p ~/.R
        - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
        - echo 'options(Ncpus = 2)' > ~/.Rprofile
        - echo 'options(repos = c(CRAN = "https://cran.rstudio.com"))' > ~/.Rprofile
        - echo 'utils::chooseCRANmirror(ind = 1)' > ~/.Rprofile
      script: true
      name: "Build dependencies and cache"
      #    - stage: "Check"
      #r_build_args: --no-build-vignettes --no-manual
      #r_check_args: --as-cran --no-build-vignettes --no-vignettes --no-manual --no-tests
      #before_script: rm -rf vignettes
      #install: skip
      #name: "examples"
      # - install: skip
      #script:
      #  - travis_wait 10 R CMD build --no-build-vignettes --no-manual .
      #  - travis_wait 40 R CMD check --as-cran --no-build-vignettes --no-vignettes --no-manual --no-codoc --no-examples xcms*tar.gz
      #before_script: rm -rf vignettes
      #name: "tests"
      #- r_build_args:
      #r_check_args: --as-cran --no-build-vignettes --no-codoc --no-examples --no-tests
      #install: skip
      #name: "vignettes"
      #- stage: "CodeCov"
      #install: skip
      #script:
      #  - R CMD INSTALL .
      #  - travis_wait 40 Rscript -e 'covr::codecov()'
      #name: "codecov"
      #on:
      #  branch: master

# In general the r-travis script automatically dump the logs after failure but
# because of a bug in travis the output is often truncated. See
# https://github.com/travis-ci/travis-ci/issues/6018
after_failure: sleep 10        


## adding this - because there were issues installing mzR
after_success:
   - Rscript -e 'covr::codecov()'
