# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r: bioc-devel 
latex: false
dist: trusty

before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

apt_packages:
  - libnetcdf-dev
  - netcdf-bin 
  - libhdf5-dev
  - libgit2-dev # git2r
  - texlive-latex-recommended
  - texlive-fonts-extra


bioc_packages:
  - mzR
  - MSnbase

## adding this - because there were issues installing mzR
after_success:
   - Rscript -e 'covr::codecov()'
