# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel 
latex: false

apt_packages:
  - libnetcdf-dev
  - netcdf-bin 
  - libhdf5-dev
  - texlive-latex-recommended
  - texlive-fonts-extra

## adding this - because there were issues installing mzR
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

after_success:
   - Rscript -e 'covr::codecov()'
