# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# using https://github.com/sneumann/xcms/blob/master/.travis.yml as a template
language: r
r: bioc-devel
cache:
  packages: true
sudo: required
warnings_are_errors: false
dist: trusty

# unfortunately apt packages are not cached
# we could use these build dependencies just in the "Build" stage and
# install their runtime libraries counter parts in "Check" but that would make
# the script more complicated and saves just a few seconds
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 [xerus] it is part of libnetcdf-dev)
      - libhdf5-dev
      - libgit2-dev # git2r
      - texlive-latex-recommended
      - texlive-fonts-extra



## adding this - because there were issues installing mzR
after_success:
   - Rscript -e 'covr::codecov()'
