#' header
#'
#' A feature table containing metadata from one of the mmetspData package
#' files used for examples, tests, and vignettes in this package.
#'
#' @format A data frame with 926 rows and 30 variables
#' @source data-raw/makeAutotunerTestData.R
"header"

#' mzDb
#'
#' A list containing all scan information from one of the mmetspData package
#' files used for examples, tests, and vignettes in this package.
#'
#' @format A list with length 926
#' @source data-raw/makeAutotunerTestData.R
"mzDb"

#' observedPeak
#'
#' A list containing peak start and end times for one peak of the mmetspData
#' package files used for examples, tests, and vignettes in this package.
#'
#' @format A list with length 2
#' \describe{
#'   \item{start}{56.18}
#'   \item{end}{97.73}
#' }
#' @source data-raw/makeAutotunerTestData.R
"observedPeak"

#' peak_table
#'
#' A data.frame generated by during the peak identification phase of Autotuner
#' package files used for examples, tests, and vignettes in this package.
#'
#' @format A data frame with 30 rows and 9 columns
#' @source data-raw/makeTestData.R
"peak_table"

#' peak_difference
#'
#' A data.frame generated by during the peak identification phase of Autotuner
#' package files used for examples, tests, and vignettes in this package.
#'
#' @format A data frame with 7 rows and 9 columns
#' @source data-raw/makeTestData.R
"peak_difference"

#' Autotuner
#'
#' Autouner object used to test functions contained within the package. The
#' content of this object was made using the mmetspData package.
#'
#' @format An Autotuner object
#' @source data-raw/makeTestData.R
"Autotuner"

